In [ ]:

Unsupervised Machine Learning - KMeans

Support vector machines (SVMs) are a set of supervised learning methods used for classification, regression and outliers detection. SVMs are one of the most robust prediction methods.

Sources: sklearn, wikipedia

kmeans.png
In [ ]:


In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:

# Take make moons in built dataset

data_ =

In [3]:

# check the dataset

data_

Out[3]:

(array([[-3.45365054e-01,  9.38468422e-01],
        [ 9.26916757e-01,  3.75267005e-01],
        [ 3.27051370e-02,  2.46345416e-01],
        [ 7.15472413e-01, -4.58667853e-01],
        [-3.20515776e-02,  9.99486216e-01],
        [ 9.97945393e-01,  6.40702200e-02],
        [ 1.94905575e+00,  1.84891782e-01],
        [ 1.61911895e-01, -4.55349012e-02],
        [ 9.67294863e-01,  2.53654584e-01],
        [ 5.72116660e-01,  8.20172255e-01],
        [ 7.61445958e-01,  6.48228395e-01],
        [ 8.40400105e-01, -4.87181783e-01],
        [ 2.00000000e+00,  5.00000000e-01],
        [ 8.38088105e-01,  5.45534901e-01],
        [ 1.57211666e+00, -3.20172255e-01],
        [-7.61445958e-01,  6.48228395e-01],
        [-9.97945393e-01,  6.40702200e-02],
        [-9.91790014e-01,  1.27877162e-01],
        [-4.62538290e-01,  8.86599306e-01],
        [-2.22520934e-01,  9.74927912e-01],
        [ 1.34536505e+00, -4.38468422e-01],
        [ 5.95216657e-01, -4.14412623e-01],
        [ 9.00968868e-01,  4.33883739e-01],
        [ 8.01413622e-01,  5.98110530e-01],
        [ 2.84527587e-01,  9.58667853e-01],
        [-6.72300890e-01,  7.40277997e-01],
        [ 7.30832427e-02,  1.24732995e-01],
        [ 1.15959990e+00, -4.87181783e-01],
        [ 8.71318704e-01,  4.90717552e-01],
        [ 7.18349350e-01,  6.95682551e-01],
        [ 1.98586378e-01, -9.81105305e-02],
        [ 1.71834935e+00, -1.95682551e-01],
        [ 3.20515776e-02,  9.99486216e-01],
        [ 9.67948422e-01, -4.99486216e-01],
        [ 1.87131870e+00,  9.28244800e-03],
        [ 1.76144596e+00, -1.48228395e-01],
        [-1.59599895e-01,  9.87181783e-01],
        [-5.72116660e-01,  8.20172255e-01],
        [ 3.45365054e-01,  9.38468422e-01],
        [ 1.99179001e+00,  3.72122838e-01],
        [ 6.23489802e-01,  7.81831482e-01],
        [ 4.04783343e-01,  9.14412623e-01],
        [ 5.09442530e-02,  1.84891782e-01],
        [ 6.72300890e-01,  7.40277997e-01],
        [ 9.90311321e-02,  6.61162609e-02],
        [-9.00968868e-01,  4.33883739e-01],
        [-8.71318704e-01,  4.90717552e-01],
        [ 7.77479066e-01, -4.74927912e-01],
        [-8.38088105e-01,  5.45534901e-01],
        [-9.81559157e-01,  1.91158629e-01],
        [ 4.81607432e-01, -3.55142763e-01],
        [ 1.28452759e+00, -4.58667853e-01],
        [-8.01413622e-01,  5.98110530e-01],
        [-2.84527587e-01,  9.58667853e-01],
        [ 2.81650650e-01, -1.95682551e-01],
        [ 1.46253829e+00, -3.86599306e-01],
        [ 9.81559157e-01,  1.91158629e-01],
        [ 1.84408430e-02,  3.08841371e-01],
        [ 1.59599895e-01,  9.87181783e-01],
        [ 2.05460725e-03,  4.35929780e-01],
        [ 1.92691676e+00,  1.24732995e-01],
        [-1.00000000e+00,  1.22464680e-16],
        [ 1.51839257e+00, -3.55142763e-01],
        [ 1.98155916e+00,  3.08841371e-01],
        [ 9.03976974e-01, -4.95379113e-01],
        [ 4.62538290e-01,  8.86599306e-01],
        [ 9.91790014e-01,  1.27877162e-01],
        [ 8.20998618e-03,  3.72122838e-01],
        [-9.49055747e-01,  3.15108218e-01],
        [-9.67294863e-01,  2.53654584e-01],
        [ 1.28681296e-01,  9.28244800e-03],
        [ 1.96729486e+00,  2.46345416e-01],
        [ 6.54634946e-01, -4.38468422e-01],
        [ 1.40478334e+00, -4.14412623e-01],
        [ 1.09602303e+00, -4.95379113e-01],
        [-6.23489802e-01,  7.81831482e-01],
        [ 5.37461710e-01, -3.86599306e-01],
        [-4.04783343e-01,  9.14412623e-01],
        [ 4.27883340e-01, -3.20172255e-01],
        [-5.18392568e-01,  8.55142763e-01],
        [ 1.00000000e+00,  0.00000000e+00],
        [ 9.49055747e-01,  3.15108218e-01],
        [-7.18349350e-01,  6.95682551e-01],
        [ 1.03205158e+00, -4.99486216e-01],
        [ 1.83808810e+00, -4.55349012e-02],
        [-9.26916757e-01,  3.75267005e-01],
        [ 1.67230089e+00, -2.40277997e-01],
        [ 1.22252093e+00, -4.74927912e-01],
        [ 1.80141362e+00, -9.81105305e-02],
        [ 9.60230259e-02,  9.95379113e-01],
        [ 2.22520934e-01,  9.74927912e-01],
        [ 1.90096887e+00,  6.61162609e-02],
        [ 3.27699110e-01, -2.40277997e-01],
        [-9.60230259e-02,  9.95379113e-01],
        [ 2.38554042e-01, -1.48228395e-01],
        [ 0.00000000e+00,  5.00000000e-01],
        [ 1.62348980e+00, -2.81831482e-01],
        [ 3.76510198e-01, -2.81831482e-01],
        [ 5.18392568e-01,  8.55142763e-01],
        [ 1.99794539e+00,  4.35929780e-01]]),
 array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1], dtype=int64))

In [4]:

# create input dataframe

inputData =

In [5]:

inputData.head()

Out[5]:
	0 	1
0 	-0.345365 	0.938468
1 	0.926917 	0.375267
2 	0.032705 	0.246345
3 	0.715472 	-0.458668
4 	-0.032052 	0.999486
In [8]:

# create output dataframe

outputData = 
outputData.head()

Out[8]:
	0
0 	0
1 	0
2 	1
3 	1
4 	0
In [9]:

# create a scatter plot for inputData set

Out[9]:

<matplotlib.collections.PathCollection at 0x1a38e535ac0>

In [10]:

# create a scatter plot for inputData set with outputData color

Out[10]:

<matplotlib.collections.PathCollection at 0x1a38e5948b0>

In [ ]:


In [11]:

# Call the sklearn Kmeans and make a model with 200 samples


#model_fit

Out[11]:

KMeans(n_clusters=5)

In [12]:

# check for labels

Out[12]:

array([1, 0, 1, 3, 1, 0, 2, 3, 0, 0, 0, 3, 2, 0, 2, 4, 4, 4, 1, 1, 2, 3,
       0, 0, 1, 4, 3, 2, 0, 0, 3, 2, 1, 3, 2, 2, 1, 4, 1, 2, 0, 1, 1, 0,
       3, 4, 4, 3, 4, 4, 3, 2, 4, 1, 3, 2, 0, 1, 1, 1, 2, 4, 2, 2, 3, 1,
       0, 1, 4, 4, 3, 2, 3, 2, 3, 4, 3, 1, 3, 4, 0, 0, 4, 3, 2, 4, 2, 2,
       2, 1, 1, 2, 3, 1, 3, 1, 2, 3, 1, 2])

In [13]:


In [14]:

# call metrics and check silhoutte score

Out[14]:

0.4734072067815621

In [15]:

# create a scatter plot for inputData set with model labels color

Out[15]:

<matplotlib.collections.PathCollection at 0x1a38ff9f7c0>

finding right number of cluster
In [16]:

cluster_range = range(1, 20)
error_list = []

for i in cluster_range:
    model = KMeans(n_clusters=i)
    model.fit(inputData)
    res = model.inertia_
    error_list.append(res)

In [17]:

import matplotlib.pyplot as plt

plt.plot(cluster_range, error_list, marker = "o", color = "g", markersize = 10)
plt.xlabel("Cluster Range")
plt.ylabel("IntraCluster Sum")
plt.title("KMeans")
plt.show()

In [ ]:


In [ ]:


